//! Native Rust Groth16 prover — Phase 3 (final).
//!
//! ## Why a hand-rolled prover (not arkworks `Groth16::prove`)
//!
//! snarkjs's QAP reduction does *not* match arkworks 0.4's:
//!
//!   * snarkjs encodes the H-bases (zkey section 0x09) as
//!     `domainSize` G1 points indexed over the **double-cover coset**
//!     (`α · ω^i`, `α = Fr.w[power+1]` when `power < Fr.s`, else `nqr²`);
//!     arkworks's `h_query` has length `domain_size − 1` and is laid out
//!     over the standard domain.
//!   * snarkjs's `buildABC1` produces sparse `A·w`, `B·w` polynomials of
//!     length `domain_size`, computes `C·w` as the **pointwise** product
//!     `A_T[i] · B_T[i]` (the residue `(A·w · B·w) mod Z(X)` is exactly
//!     this size-N interpolant), then runs `IFFT → coset shift → FFT`
//!     to get coset evaluations; arkworks's `r1cs_to_qap` derives `C`
//!     from the `C` part of the R1CS directly.
//!
//! The two paths yield mathematically different intermediate polynomials,
//! so even though both end at a *valid* Groth16 proof, the produced
//! `(A, B, C)` triple from one prover is **not** the same group elements
//! as the triple from the other when the bases were generated by the
//! other party's setup. Trying to call `ark_groth16::Groth16::prove` on
//! a snarkjs-produced `.zkey` yields bytes that decode cleanly but fail
//! the pairing check — exactly the failure mode the previous Phase 3
//! attempt hit.
//!
//! This module therefore reimplements the snarkjs algorithm step-for-step
//! in Rust using arkworks Fr/G1/G2 primitives and `ark-poly`
//! `Radix2EvaluationDomain`, so its output is **bit-identical** to
//! snarkjs `groth16.prove` modulo the randomness choice (`r`, `s` in Fr).
//!
//! See the in-line comments for the exact correspondence with
//! `snarkjs/src/groth16_prove.js` (sections labelled "snarkjs step N").

use ark_bn254::{Fr, G1Affine, G1Projective, G2Affine, G2Projective};
use ark_ec::{CurveGroup, VariableBaseMSM};
use ark_ff::{FftField, Field, One, PrimeField, UniformRand, Zero};
use ark_poly::{EvaluationDomain, Radix2EvaluationDomain};
use rand::{RngCore, SeedableRng};
use rand_chacha::ChaCha20Rng;
use tracing::{instrument, trace};

use crate::error::{ZacError, ZacResult};
use crate::iden3::wtns::Wtns;
use crate::iden3::zkey::Zkey;

/// Seed for the deterministic ChaCha20 RNG that picks the prover's
/// blinding scalars `r, s`. Fixed at 0 so two independent invocations on
/// the same `(zkey, wtns)` produce **bit-identical** proofs — this is
/// what makes Criterion regressions detectable and what lets the bench
/// run the full prove() in a loop without flakiness.
///
/// Security note: `r`, `s` are SOUNDNESS blindings, not honest-verifier
/// hiding randomness — Groth16 is statistically-zero-knowledge regardless
/// of `r, s`, so a fixed seed does not weaken the proof system. Deployments
/// that need full ZK should reseed from `OsRng`.
pub const RNG_SEED: u64 = 0;

/// Compute the three Groth16 group elements `(A, B, C)` natively in Rust.
///
/// Returns the affine triple in arkworks form. Caller is responsible for
/// serializing them (e.g. via `CanonicalSerialize::serialize_compressed`)
/// into the 128-byte `.zacp` proof block.
///
/// Mirrors `snarkjs/src/groth16_prove.js` step-for-step; see RNG_SEED
/// for the determinism caveat.
#[instrument(level = "trace", skip(zkey, wtns))]
pub fn groth16_native_prove(zkey: &Zkey, wtns: &Wtns) -> ZacResult<(G1Affine, G2Affine, G1Affine)> {
    let mut rng = ChaCha20Rng::seed_from_u64(RNG_SEED);
    groth16_native_prove_with_rng(zkey, wtns, &mut rng)
}

/// Same as [`groth16_native_prove`] but with caller-provided randomness for
/// the Groth16 blinding scalars `r, s`.
///
/// Pass `&mut ChaCha20Rng::seed_from_u64(RNG_SEED)` for deterministic
/// regression-friendly proofs, or `&mut rand::rngs::OsRng` for
/// production-grade ZK hiding (the proof system is still SZK, but a fresh
/// `(r, s)` per call is cheap insurance).
#[instrument(level = "trace", skip(zkey, wtns, rng))]
pub fn groth16_native_prove_with_rng<R: RngCore>(
    zkey: &Zkey,
    wtns: &Wtns,
    rng: &mut R,
) -> ZacResult<(G1Affine, G2Affine, G1Affine)> {
    let n = zkey.domain_size as usize;
    let n_vars = zkey.n_vars as usize;
    let n_public = zkey.n_public as usize;

    if wtns.values.len() != n_vars {
        return Err(ZacError::PublicInputCountMismatch {
            offset: 0,
            declared: wtns.values.len() as u64,
            expected: n_vars as u64,
        });
    }
    if wtns.values[0] != Fr::one() {
        return Err(ZacError::NonCanonicalFr {
            offset: 0,
            input_index: 0,
        });
    }

    // -----------------------------------------------------------------
    // snarkjs step 1 — buildABC1
    //
    //   for each coef (m, c, s, v):
    //       out[m][c] += v * w[s]
    //   C_T[i] = A_T[i] * B_T[i] for i in 0..domainSize
    // -----------------------------------------------------------------
    let mut a_t = vec![Fr::zero(); n];
    let mut b_t = vec![Fr::zero(); n];
    for coef in &zkey.coefs {
        let term = coef.value * wtns.values[coef.signal as usize];
        match coef.matrix {
            0 => a_t[coef.constraint as usize] += term,
            1 => b_t[coef.constraint as usize] += term,
            other => {
                return Err(ZacError::BadFlags {
                    offset: 0,
                    field: "zkey.coef.matrix",
                    value: other as u64,
                });
            }
        }
    }
    let mut c_t = vec![Fr::zero(); n];
    for i in 0..n {
        c_t[i] = a_t[i] * b_t[i];
    }
    trace!(n, "groth16_prover: buildABC1 done");

    // -----------------------------------------------------------------
    // snarkjs step 2 — IFFT → coset shift (batchApplyKey) → FFT
    //
    //   inc = power == Fr.s ? Fr.shift (= nqr²) : Fr.w[power+1]
    //
    // arkworks `Radix2EvaluationDomain::group_gen` is `Fr.w[power]`
    // (the primitive `n`-th root), so `Fr.w[power+1]` is its
    // **square root** in the 2^(power+1) subgroup: solve
    // `x^2 = group_gen` over Fr. We pick the same branch snarkjs picks
    // by walking down from `Fr::TWO_ADIC_ROOT_OF_UNITY` via repeated
    // squaring (`Fr.w[s], Fr.w[s-1], …, Fr.w[power+1]`).
    // -----------------------------------------------------------------
    let domain = Radix2EvaluationDomain::<Fr>::new(n).ok_or(ZacError::ProofRejected {
        reason: "Radix2EvaluationDomain: bad domain size",
    })?;
    let inc = compute_coset_shift(n);
    trace!(
        n,
        domain_gen = ?domain.group_gen,
        inc_le = ?fr_le_hex(&inc),
        "groth16_prover: domain + coset shift"
    );

    let a_odd = coset_evaluations(&domain, &a_t, inc);
    let b_odd = coset_evaluations(&domain, &b_t, inc);
    let c_odd = coset_evaluations(&domain, &c_t, inc);
    trace!(n, "groth16_prover: coset FFT (3x) done");

    // -----------------------------------------------------------------
    // snarkjs step 3 — joinABC, followed by the **R^(−2) compensation**
    //
    //   P_odd[i] = A_odd[i] * B_odd[i] - C_odd[i]
    //
    // No division by Z(α · ω^i) here: that constant factor
    // `(α^n − 1)` is already baked into the H_query bases by the
    // snarkjs setup (zkey section 0x09).
    //
    // ## The R^(−2) trick (CRITICAL for snarkjs interop)
    //
    // snarkjs's `buildABC1` calls `Fr.mul(coef_mont, witness_std)`. With the
    // Montgomery convention `mul(a, b) = a·b/R`, that yields **standard-form
    // bytes** for `coef·w`. Then `Fr.ifft`, `batchApplyKey`, and `Fr.fft`
    // operate on those bytes by **treating them as Montgomery
    // representations** (since ffjavascript's wasm Fr always works in the
    // Mont domain). So the abstract field value at each byte position
    // throughout the FFT pipeline is `(real value)/R`. After joinABC the
    // bytes have abstract value `H(α·ω^i)·Z(α·ω^i)/R²`. Finally
    // `frm_batchFromMontgomery` divides by R once more, so the bytes
    // arriving at the H-MSM as **standard-form scalars** are
    //
    //     scalar_i = H(α·ω^i) · Z(α·ω^i) / R²    (mod r)
    //
    // The H-bases in zkey section 0x09 are scaled to absorb this factor of
    // R² so that the final MSM produces the right group element.
    //
    // arkworks operates on abstract field values, not Montgomery bytes, so
    // a naïve port computes `p_odd[i] = H(α·ω^i) · Z(α·ω^i)` directly —
    // i.e. R² too large for the snarkjs-encoded bases. We compensate by
    // dividing every `p_odd[i]` by R² mod r, recovering the exact same
    // scalars snarkjs hands to its MSM.
    //
    // This was the trickiest part of the port — it cost us several hours
    // of intermediate-value diffing (see `node-tools/check_msms.mjs` and
    // `crates/zac/examples/_dbg_native.rs` in git history) before the
    // R² factor revealed itself in the dump comparison.
    // -----------------------------------------------------------------
    let mut p_odd = vec![Fr::zero(); n];
    for i in 0..n {
        p_odd[i] = a_odd[i] * b_odd[i] - c_odd[i];
    }
    let r_inv = r_inv_fr();
    let r_inv2 = r_inv * r_inv;
    for x in p_odd.iter_mut() {
        *x *= r_inv2;
    }
    trace!(n, "groth16_prover: joinABC + R^(-2) compensation done");

    // -----------------------------------------------------------------
    // snarkjs step 4 — MSMs
    //
    //   pi_a   = α_G1 + Σ A_query[i] · w[i]                      + r · δ_G1
    //   pi_b   = β_G2 + Σ B2_query[i] · w[i]                     + s · δ_G2
    //   pib1   = β_G1 + Σ B1_query[i] · w[i]                     + s · δ_G1
    //   pi_c   = Σ C_query[i] · w[i + nPublic + 1] + H + s·pi_a + r·pib1
    //            − r · s · δ_G1
    //
    // We use arkworks `VariableBaseMSM::msm` (Pippenger). Same arithmetic
    // as `ffjavascript`'s `multiExpAffine`.
    // -----------------------------------------------------------------
    let w = &wtns.values;
    let a_msm = msm_g1(&zkey.a_query, w)?;
    let b1_msm = msm_g1(&zkey.b_g1_query, w)?;
    let b2_msm = msm_g2(&zkey.b_g2_query, w)?;
    let c_msm = msm_g1(&zkey.c_query, &w[(n_public + 1)..])?;
    let h_msm = msm_g1(&zkey.h_query, &p_odd)?;
    trace!("groth16_prover: 5x MSM done");

    // -----------------------------------------------------------------
    // snarkjs step 5 — assemble final group elements
    // -----------------------------------------------------------------
    let r = Fr::rand(rng);
    let s = Fr::rand(rng);
    // Phase 5 redaction: blinding scalars `r` and `s` are secret inputs to
    // the Groth16 proof — leaking them lets an attacker correlate proofs to
    // the prover's secrets. Even at TRACE level, the raw values must never
    // hit a log; emit only 8-byte BLAKE3 fingerprints so a developer can
    // distinguish runs without seeing the bytes themselves.
    trace!(
        r_fp = %hex::encode(&blake3::hash(fr_le_hex(&r).as_bytes()).as_bytes()[..8]),
        s_fp = %hex::encode(&blake3::hash(fr_le_hex(&s).as_bytes()).as_bytes()[..8]),
        "groth16_prover: sampled blinding scalars (truncated fingerprints)"
    );

    let alpha_g1: G1Projective = zkey.alpha_g1.into();
    let beta_g1: G1Projective = zkey.beta_g1.into();
    let beta_g2: G2Projective = zkey.beta_g2.into();
    let delta_g1: G1Projective = zkey.delta_g1.into();
    let delta_g2: G2Projective = zkey.delta_g2.into();

    let pi_a_proj = a_msm + alpha_g1 + delta_g1 * r;
    let pi_b_proj = b2_msm + beta_g2 + delta_g2 * s;
    let pib1_proj = b1_msm + beta_g1 + delta_g1 * s;

    let pi_a_aff = pi_a_proj.into_affine();
    let pi_b_aff = pi_b_proj.into_affine();

    let mut pi_c_proj = c_msm + h_msm;
    pi_c_proj += pi_a_proj * s;
    pi_c_proj += pib1_proj * r;
    pi_c_proj -= delta_g1 * (r * s);
    let pi_c_aff = pi_c_proj.into_affine();

    Ok((pi_a_aff, pi_b_aff, pi_c_aff))
}

// ---------------------------------------------------------------------------
// helpers — FFT, MSM, coset shift
// ---------------------------------------------------------------------------

/// `Σ p_odd_T[i] · bases[i]` over G1 using arkworks Pippenger MSM.
fn msm_g1(bases: &[G1Affine], scalars: &[Fr]) -> ZacResult<G1Projective> {
    if bases.len() != scalars.len() {
        return Err(ZacError::ProofRejected {
            reason: "msm_g1: bases.len() != scalars.len()",
        });
    }
    G1Projective::msm(bases, scalars).map_err(|_| ZacError::ProofRejected {
        reason: "msm_g1: arkworks MSM rejected (lengths)",
    })
}

fn msm_g2(bases: &[G2Affine], scalars: &[Fr]) -> ZacResult<G2Projective> {
    if bases.len() != scalars.len() {
        return Err(ZacError::ProofRejected {
            reason: "msm_g2: bases.len() != scalars.len()",
        });
    }
    G2Projective::msm(bases, scalars).map_err(|_| ZacError::ProofRejected {
        reason: "msm_g2: arkworks MSM rejected (lengths)",
    })
}

/// `R^(−1) mod r` where `R = 2^256` is the snarkjs/iden3 Montgomery
/// constant. Re-derives the value by doubling `1` 256 times to get `R mod r`
/// and inverting — keeps this self-contained and lets us avoid pulling
/// snarkjs's constant into the workspace as a magic number.
fn r_inv_fr() -> Fr {
    let mut r = Fr::one();
    for _ in 0..256 {
        r += r;
    }
    r.inverse().expect("2^256 mod r is nonzero")
}

/// snarkjs's "double-cover" coset evaluation:
///
///   inc = power == Fr.s ? Fr.shift : Fr.w[power+1]
///
/// We compute `inc` by walking the snarkjs `w[]` table:
///   * `w[s]   = Fr::TWO_ADIC_ROOT_OF_UNITY`        (primitive 2^s-th root)
///   * `w[i]   = w[i+1]^2`                          (descend)
///   * `w[s+1]` does NOT exist (s is the 2-adicity), so when `power == s`
///     snarkjs falls back to `Fr.shift = nqr² = 25` (since BN254 Fr `nqr = 5`).
fn compute_coset_shift(domain_size: usize) -> Fr {
    let power = (domain_size.trailing_zeros()) as usize;
    let s = Fr::TWO_ADICITY as usize;
    if power == s {
        // nqr² mod r. BN254 Fr's smallest quadratic non-residue is 5;
        // 5² = 25.
        return Fr::from(25u64);
    }
    // power < s: descend from Fr.w[s] to Fr.w[power+1] via repeated squaring.
    // w[s] = TWO_ADIC_ROOT_OF_UNITY, w[s-1] = w[s]², …, w[power+1] = w[power+2]².
    let mut w = Fr::TWO_ADIC_ROOT_OF_UNITY;
    let steps = s - (power + 1);
    for _ in 0..steps {
        w = w.square();
    }
    w
}

/// Equivalent to snarkjs's `IFFT → batchApplyKey(_, 1, inc) → FFT` pipeline
/// applied to a size-N evaluation vector `evals`.
///
/// Mathematically: let `p(X)` be the unique poly of degree ≤ N−1 with
/// `p(ω^i) = evals[i]`. Then the returned vector equals
/// `[p(inc · ω^i)]_{i=0..N}`. Useful for QAP "double-cover" evaluations.
fn coset_evaluations(domain: &Radix2EvaluationDomain<Fr>, evals: &[Fr], inc: Fr) -> Vec<Fr> {
    // 1. IFFT to recover monomial coefficients.
    let coeffs = domain.ifft(evals);
    // 2. Scale coefficients by inc^i ("batchApplyKey").
    let mut scaled = coeffs;
    let mut power = Fr::one();
    for c in scaled.iter_mut() {
        *c *= power;
        power *= inc;
    }
    // 3. Forward FFT to get evaluations on the coset {inc · ω^i}.
    domain.fft(&scaled)
}

fn fr_le_hex(x: &Fr) -> String {
    use ark_ff::BigInteger;
    let bytes = x.into_bigint().to_bytes_le();
    hex::encode(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_ff::UniformRand;

    #[test]
    fn coset_shift_squared_equals_domain_gen_for_subdomain() {
        // Smoke: for power < Fr::TWO_ADICITY, compute_coset_shift(n)
        // should satisfy `inc² == Radix2EvaluationDomain(n).group_gen`.
        // (snarkjs invariant: Fr.w[power+1]² == Fr.w[power].)
        for &n in &[2usize, 4, 8, 16, 64, 1024] {
            let dom = Radix2EvaluationDomain::<Fr>::new(n).unwrap();
            let inc = compute_coset_shift(n);
            assert_eq!(
                inc.square(),
                dom.group_gen,
                "inc² must equal group_gen for n={n}"
            );
        }
    }

    #[test]
    fn coset_evaluations_match_direct_eval() {
        // Sanity: build a random degree-(n-1) polynomial, evaluate it at
        // ω^i and then run coset_evaluations to evaluate at α·ω^i.
        // Compare to a direct Horner evaluation.
        let mut rng = ChaCha20Rng::seed_from_u64(42);
        let n = 8usize;
        let dom = Radix2EvaluationDomain::<Fr>::new(n).unwrap();
        let coeffs: Vec<Fr> = (0..n).map(|_| Fr::rand(&mut rng)).collect();
        // Build evals = [p(ω^i)] manually.
        let omega = dom.group_gen;
        let mut evals = Vec::with_capacity(n);
        let mut x = Fr::one();
        for _ in 0..n {
            evals.push(eval_horner(&coeffs, x));
            x *= omega;
        }
        // Use coset_evaluations to get [p(inc · ω^i)].
        let inc = compute_coset_shift(n);
        let got = coset_evaluations(&dom, &evals, inc);
        // Direct check.
        let mut want = Vec::with_capacity(n);
        let mut y = inc;
        for _ in 0..n {
            want.push(eval_horner(&coeffs, y));
            y *= omega;
        }
        assert_eq!(got, want);
    }

    fn eval_horner(coeffs: &[Fr], x: Fr) -> Fr {
        let mut acc = Fr::zero();
        for c in coeffs.iter().rev() {
            acc = acc * x + *c;
        }
        acc
    }
}
